from dataclasses import dataclass
from enum import Enum


class EventType(str, Enum):
    MISSION_REQUESTED = "MISSION_REQUESTED"
    MISSION_LOADED = "MISSION_LOADED"
    MISSION_INVALID = "MISSION_INVALID"
    NAV2_READY = "NAV2_READY"
    NAV2_NOT_READY = "NAV2_NOT_READY"
    GOAL_SENT = "GOAL_SENT"
    GOAL_REJECTED = "GOAL_REJECTED"
    FEEDBACK_TICK = "FEEDBACK_TICK"
    GOAL_SUCCEEDED = "GOAL_SUCCEEDED"
    GOAL_FAILED = "GOAL_FAILED"
    GOAL_TIMEOUT = "GOAL_TIMEOUT"
    SAFETY_STOP = "SAFETY_STOP"
    SAFETY_CLEAR = "SAFETY_CLEAR"
    ACTION_CANCEL_REQUESTED = "ACTION_CANCEL_REQUESTED"
    ACTION_CANCEL_CONFIRMED = "ACTION_CANCEL_CONFIRMED"


@dataclass(frozen=True)
class Event:
    type: EventType
    reason: str = ""
