from enum import Enum


class MissionState(str, Enum):
    IDLE = "IDLE"
    LOADING_MISSION = "LOADING_MISSION"
    WAITING_FOR_NAV2 = "WAITING_FOR_NAV2"
    DISPATCHING_GOAL = "DISPATCHING_GOAL"
    WAITING_FOR_RESULT = "WAITING_FOR_RESULT"
    CANCELING_FOR_SAFETY = "CANCELING_FOR_SAFETY"
    PAUSED_FOR_SAFETY = "PAUSED_FOR_SAFETY"
    RETRYING_GOAL = "RETRYING_GOAL"
    SKIPPING_GOAL = "SKIPPING_GOAL"
    MISSION_SUCCEEDED = "MISSION_SUCCEEDED"
    MISSION_FAILED = "MISSION_FAILED"
    MISSION_CANCELED = "MISSION_CANCELED"
